# Use root/example as user/password credentials
version: '3.1'

services:

  mysql-standalone:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
      MYSQL_USER: sa
      MYSQL_PASSWORD: password

  users-mysql:
    image: users-mysql
    restart: always
    ports:
      - 8086:8086
    depends_on: 
      - mysql-standalone
    links: 
      - mysql-standalone:users-mysql
