# Use root/example as user/password credentials
version: '3.1'

services:

  mysql:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: demo
      MYSQL_USER: demo_user
      MYSQL_PASSWORD: demo_pass
    networks: 
      - default

  demo-mysql:
    image: ehcoo/spring-boot-docker-mysql
    restart: always
    ports:
      - 8080:8080
    depends_on: 
      - mysql
    links: 
      - mysql:demo-mysql
    networks: 
      - default
